items:
- uid: System.IO.FileNotFoundException
  commentId: T:System.IO.FileNotFoundException
  id: FileNotFoundException
  parent: System.IO
  children:
  - System.IO.FileNotFoundException.#ctor
  - System.IO.FileNotFoundException.#ctor(System.String)
  - System.IO.FileNotFoundException.#ctor(System.String,System.Exception)
  - System.IO.FileNotFoundException.#ctor(System.String,System.String)
  - System.IO.FileNotFoundException.#ctor(System.String,System.String,System.Exception)
  - System.IO.FileNotFoundException.FileName
  - System.IO.FileNotFoundException.Message
  - System.IO.FileNotFoundException.ToString
  langs:
  - csharp
  - vb
  name: FileNotFoundException
  fullName: System.IO.FileNotFoundException
  type: Class
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: FileNotFoundException
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2641
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>The exception that is thrown when an attempt to access a file that does not exist on disk fails.</p>\n"
  remarks: "\n<p>\n<strong>FileNotFoundException</strong> uses the HRESULT COR_E_FILENOTFOUND which has the value 0x80070002.</p>\n<p>If your code does not have <xref href=\"System.Security.Permissions.FileIOPermissionAttribute.PathDiscovery\" data-throw-if-not-resolved=\"false\"></xref> permission, the error message for this exception may only contain file or directory names instead of fully qualified paths.</p>\n"
  syntax:
    content: 'public class FileNotFoundException : IOException'
    content.vb: >-
      Public Class FileNotFoundException
          Inherits IOException
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  inheritance:
  - System.Object
  - System.Exception
  - System.IO.IOException
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.GetBaseException
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.IO.FileNotFoundException.#ctor
  commentId: M:System.IO.FileNotFoundException.#ctor
  id: '#ctor'
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: FileNotFoundException()
  fullName: System.IO.FileNotFoundException.FileNotFoundException()
  type: Constructor
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2643
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref> class with its message string set to a system-supplied message and its HRESULT set to COR_E_FILENOTFOUND.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.IO.FileNotFoundException.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"Could not find the specified file.\" This message takes into account the current system culture.</p>\n"
  syntax:
    content: public FileNotFoundException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.FileNotFoundException.#ctor(System.String)
  commentId: M:System.IO.FileNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: FileNotFoundException(String)
  fullName: System.IO.FileNotFoundException.FileNotFoundException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2644
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref> class with its message string set to <em>message</em> and its HRESULT set to COR_E_FILENOTFOUND.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.IO.FileNotFoundException.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance using <em>message</em>.</p>\n"
  syntax:
    content: public FileNotFoundException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A description of the error. The content of <em>message</em> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.FileNotFoundException.#ctor(System.String,System.Exception)
  commentId: M:System.IO.FileNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: FileNotFoundException(String, Exception)
  fullName: System.IO.FileNotFoundException.FileNotFoundException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2645
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The inner exception reference. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n<p>For more information on inner exceptions, see <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: public FileNotFoundException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A description of the error. The content of <em>message</em> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. </p>\n"
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>innerException</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.FileNotFoundException.#ctor(System.String,System.String)
  commentId: M:System.IO.FileNotFoundException.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: FileNotFoundException(String, String)
  fullName: System.IO.FileNotFoundException.FileNotFoundException(System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2646
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref> class with its message string set to <em>message</em>, specifying the file name that cannot be found, and its HRESULT set to COR_E_FILENOTFOUND.</p>\n"
  remarks: "\n<p>The constructor initializes the <xref href=\"System.IO.FileNotFoundException.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance using <em>message</em> and the <xref href=\"System.IO.FileNotFoundException.FileName\" data-throw-if-not-resolved=\"false\"></xref> property using <em>fileName</em>.</p>\n"
  syntax:
    content: public FileNotFoundException(string message, string fileName)
    content.vb: Public Sub New(message As String, fileName As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A description of the error. The content of <em>message</em> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. </p>\n"
    - id: fileName
      type: System.String
      description: "\n<p>The full name of the file with the invalid image. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.FileNotFoundException.#ctor(System.String,System.String,System.Exception)
  commentId: M:System.IO.FileNotFoundException.#ctor(System.String,System.String,System.Exception)
  id: '#ctor(System.String,System.String,System.Exception)'
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: FileNotFoundException(String, String, Exception)
  fullName: System.IO.FileNotFoundException.FileNotFoundException(System.String, System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2647
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.IO.FileNotFoundException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The inner exception reference. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n<p>For more information on inner exceptions, see <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: public FileNotFoundException(string message, string fileName, Exception innerException)
    content.vb: Public Sub New(message As String, fileName As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception. </p>\n"
    - id: fileName
      type: System.String
      description: "\n<p>The full name of the file with the invalid image. </p>\n"
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>innerException</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.FileNotFoundException.FileName
  commentId: P:System.IO.FileNotFoundException.FileName
  id: FileName
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: FileName
  fullName: System.IO.FileNotFoundException.FileName
  type: Property
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: FileName
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2648
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Gets the name of the file that cannot be found.</p>\n"
  remarks: "\n<p>This property is read-only.</p>\n"
  syntax:
    content: public string FileName { get; }
    content.vb: Public ReadOnly Property FileName As String
    parameters: []
    return:
      type: System.String
      description: "\n<p>The name of the file, or <strong>null</strong> if no file name was passed to the constructor for this instance.</p>\n"
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: System.IO.FileNotFoundException.Message
  commentId: P:System.IO.FileNotFoundException.Message
  id: Message
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: Message
  fullName: System.IO.FileNotFoundException.Message
  type: Property
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Message
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2649
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Gets the error message that explains the reason for the exception.</p>\n"
  remarks: "\n<p>If no message was supplied to the constructor for the current exception, this property returns a system-supplied error message. If the <xref href=\"System.IO.FileLoadException.FileName\" data-throw-if-not-resolved=\"false\"></xref> property is not <strong>null</strong>, the message includes the file name.</p>\n<p>This property is read-only.</p>\n"
  syntax:
    content: public override string Message { get; }
    content.vb: Public Overrides ReadOnly Property Message As String
    parameters: []
    return:
      type: System.String
      description: "\n<p>The error message.</p>\n"
  overridden: System.Exception.Message
  modifiers.csharp:
  - public
  - override
  - get
  modifiers.vb:
  - Public
  - Overrides
  - ReadOnly
- uid: System.IO.FileNotFoundException.ToString
  commentId: M:System.IO.FileNotFoundException.ToString
  id: ToString
  parent: System.IO.FileNotFoundException
  langs:
  - csharp
  - vb
  name: ToString()
  fullName: System.IO.FileNotFoundException.ToString()
  type: Method
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ToString
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 2650
  assemblies:
  - System.Runtime
  namespace: System.IO
  summary: "\n<p>Returns the fully qualified name of this exception and possibly the error message, the name of the inner exception, and the stack trace.</p>\n"
  remarks: "\n<p>This method overrides <xref href=\"System.Object.ToString\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>The string representation returned by this method includes the name of the exception, the value of the <xref href=\"System.IO.FileNotFoundException.Message\" data-throw-if-not-resolved=\"false\"></xref> property, the result of calling ToString on the inner exception, the value of the <xref href=\"System.IO.FileNotFoundException.FileName\" data-throw-if-not-resolved=\"false\"></xref> property, and the result of calling <xref href=\"System.Environment.StackTrace\" data-throw-if-not-resolved=\"false\"></xref>. If any of these members is a null reference, its value is not included in the returned string.</p>\n"
  syntax:
    content: public override string ToString()
    content.vb: Public Overrides Function ToString As String
    return:
      type: System.String
      description: "\n<p>The fully qualified name of this exception and possibly the error message, the name of the inner exception, and the stack trace.</p>\n"
  overridden: System.Exception.ToString
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: System.IO
  isExternal: false
  name: System.IO
  fullName: System.IO
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
- uid: System.IO.IOException
  parent: System.IO
  isExternal: false
  name: IOException
  fullName: System.IO.IOException
- uid: System.Exception.Data
  parent: System.Exception
  isExternal: false
  name: Data
  fullName: System.Exception.Data
- uid: System.Exception.HelpLink
  parent: System.Exception
  isExternal: false
  name: HelpLink
  fullName: System.Exception.HelpLink
- uid: System.Exception.HResult
  parent: System.Exception
  isExternal: false
  name: HResult
  fullName: System.Exception.HResult
- uid: System.Exception.InnerException
  parent: System.Exception
  isExternal: false
  name: InnerException
  fullName: System.Exception.InnerException
- uid: System.Exception.Source
  parent: System.Exception
  isExternal: false
  name: Source
  fullName: System.Exception.Source
- uid: System.Exception.StackTrace
  parent: System.Exception
  isExternal: false
  name: StackTrace
  fullName: System.Exception.StackTrace
- uid: System.Exception.GetBaseException
  parent: System.Exception
  isExternal: false
  name: GetBaseException()
  fullName: System.Exception.GetBaseException()
  spec.csharp:
  - uid: System.Exception.GetBaseException
    name: GetBaseException
    fullName: System.Exception.GetBaseException
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Exception.GetBaseException
    name: GetBaseException
    fullName: System.Exception.GetBaseException
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: false
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: false
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: false
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception.Message
  parent: System.Exception
  isExternal: false
  name: Message
  fullName: System.Exception.Message
- uid: System.Exception.ToString
  parent: System.Exception
  isExternal: false
  name: ToString()
  fullName: System.Exception.ToString()
  spec.csharp:
  - uid: System.Exception.ToString
    name: ToString
    fullName: System.Exception.ToString
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Exception.ToString
    name: ToString
    fullName: System.Exception.ToString
  - name: (
    fullName: (
  - name: )
    fullName: )
