items:
- uid: System.Runtime.InteropServices.MarshalDirectiveException
  commentId: T:System.Runtime.InteropServices.MarshalDirectiveException
  id: MarshalDirectiveException
  parent: System.Runtime.InteropServices
  children:
  - System.Runtime.InteropServices.MarshalDirectiveException.#ctor
  - System.Runtime.InteropServices.MarshalDirectiveException.#ctor(System.String)
  - System.Runtime.InteropServices.MarshalDirectiveException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: MarshalDirectiveException
  fullName: System.Runtime.InteropServices.MarshalDirectiveException
  type: Class
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: MarshalDirectiveException
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 671
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>The exception that is thrown by the marshaler when it encounters a <xref href=\"System.Runtime.InteropServices.MarshalAsAttribute\" data-throw-if-not-resolved=\"false\"></xref> it does not support.</p>\n"
  remarks: "\n<p>\n<strong>MarshalDirectiveException</strong> uses the HRESULT COR_E_MARSHALDIRECTIVE which has the value 0x80131535.</p>\n"
  syntax:
    content: 'public class MarshalDirectiveException : Exception'
    content.vb: >-
      Public Class MarshalDirectiveException
          Inherits Exception
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Runtime.InteropServices.MarshalDirectiveException.#ctor
  commentId: M:System.Runtime.InteropServices.MarshalDirectiveException.#ctor
  id: '#ctor'
  parent: System.Runtime.InteropServices.MarshalDirectiveException
  langs:
  - csharp
  - vb
  name: MarshalDirectiveException()
  fullName: System.Runtime.InteropServices.MarshalDirectiveException.MarshalDirectiveException()
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 673
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>Initializes a new instance of the <strong>MarshalDirectiveException</strong> class with default properties.</p>\n"
  remarks: "\n<p>The following table shows the initial property values for an instance of <strong>MarshalDirectiveException</strong>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>A localized error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public MarshalDirectiveException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.MarshalDirectiveException.#ctor(System.String)
  commentId: M:System.Runtime.InteropServices.MarshalDirectiveException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.InteropServices.MarshalDirectiveException
  langs:
  - csharp
  - vb
  name: MarshalDirectiveException(String)
  fullName: System.Runtime.InteropServices.MarshalDirectiveException.MarshalDirectiveException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 674
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>Initializes a new instance of the <strong>MarshalDirectiveException</strong> class with a specified error message.</p>\n"
  remarks: "\n<p>The following table shows the initial property values for an instance of <strong>MarshalDirectiveException</strong>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<em>message</em>\n</p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public MarshalDirectiveException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that specifies the reason for the exception. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.MarshalDirectiveException.#ctor(System.String,System.Exception)
  commentId: M:System.Runtime.InteropServices.MarshalDirectiveException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.InteropServices.MarshalDirectiveException
  langs:
  - csharp
  - vb
  name: MarshalDirectiveException(String, Exception)
  fullName: System.Runtime.InteropServices.MarshalDirectiveException.MarshalDirectiveException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 675
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Runtime.InteropServices.MarshalDirectiveException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Runtime.InteropServices.MarshalDirectiveException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The inner exception reference. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public MarshalDirectiveException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception. </p>\n"
    - id: inner
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>inner</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Runtime.InteropServices
  isExternal: false
  name: System.Runtime.InteropServices
  fullName: System.Runtime.InteropServices
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
