items:
- uid: System.Reflection.TargetException
  commentId: T:System.Reflection.TargetException
  id: TargetException
  parent: System.Reflection
  children:
  - System.Reflection.TargetException.#ctor
  - System.Reflection.TargetException.#ctor(System.String)
  - System.Reflection.TargetException.#ctor(System.String,Exception)
  langs:
  - csharp
  - vb
  name: TargetException
  fullName: System.Reflection.TargetException
  type: Class
  source:
    remote:
      path: src/System.Reflection/ref/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: TargetException
    path: src/System.Reflection/ref/System.Reflection.cs
    startLine: 408
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>Represents the exception that is thrown when an attempt is made to invoke an invalid target.</p>\n"
  remarks: "\n<p>A <strong>TargetException</strong> is thrown when an attempt is made to invoke a non-static method on a null object. This may occur because the caller does not have access to the member, or because the target does not define the member, and so on.</p>\n<p>This exception is not included in the <see href=\"http://go.microsoft.com/fwlink/?LinkID=247912\">.NET for Windows Store apps</see> or the , but it is thrown by some members that are. To catch the exception in that case, write a <strong>catch</strong> statement for <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref> instead.</p>\n"
  syntax:
    content: 'public class TargetException : Exception'
    content.vb: >-
      Public Class TargetException
          Inherits Exception
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Reflection.TargetException.#ctor
  commentId: M:System.Reflection.TargetException.#ctor
  id: '#ctor'
  parent: System.Reflection.TargetException
  langs:
  - csharp
  - vb
  name: TargetException()
  fullName: System.Reflection.TargetException.TargetException()
  type: Constructor
  source:
    remote:
      path: src/System.Reflection/ref/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Reflection/ref/System.Reflection.cs
    startLine: 410
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Reflection.TargetException\" data-throw-if-not-resolved=\"false\"></xref> class with an empty message and the root cause of the exception.</p>\n"
  remarks: "\n<p>The <strong>InnerException</strong> property is set to <strong>null</strong> and the HRESULT error code is set to COR_E_TARGET.</p>\n<p>\n<strong>TargetException</strong> inherits from the <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref>. This constructor sets the properties of the <strong>Exception</strong> object as shown in the following table.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>\n</p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The empty string (\"\"). </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TargetException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Reflection.TargetException.#ctor(System.String)
  commentId: M:System.Reflection.TargetException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Reflection.TargetException
  langs:
  - csharp
  - vb
  name: TargetException(String)
  fullName: System.Reflection.TargetException.TargetException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Reflection/ref/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Reflection/ref/System.Reflection.cs
    startLine: 411
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Reflection.TargetException\" data-throw-if-not-resolved=\"false\"></xref> class with the given message and the root cause exception.</p>\n"
  remarks: "\n<p>\n<strong>TargetException</strong> inherits from the <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref>. This constructor sets the properties of the <strong>Exception</strong> object as shown in the following table.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>\n</p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TargetException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A <strong>String</strong> describing the reason why the exception occurred. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Reflection.TargetException.#ctor(System.String,Exception)
  commentId: M:System.Reflection.TargetException.#ctor(System.String,Exception)
  id: '#ctor(System.String,Exception)'
  parent: System.Reflection.TargetException
  langs:
  - csharp
  - vb
  name: TargetException(String, Exception)
  fullName: System.Reflection.TargetException.TargetException(System.String, Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Reflection/ref/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Reflection/ref/System.Reflection.cs
    startLine: 412
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  syntax:
    content: public TargetException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
    - id: inner
      type: Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Reflection
  isExternal: false
  name: System.Reflection
  fullName: System.Reflection
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: Exception
  isExternal: true
  name: Exception
  fullName: Exception
