items:
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  commentId: T:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  id: RuntimeBinderException
  parent: Microsoft.CSharp.RuntimeBinder
  children:
  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor
  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)
  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: RuntimeBinderException
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  type: Class
  source:
    remote:
      path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: RuntimeBinderException
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 13
  assemblies:
  - Microsoft.CSharp
  namespace: Microsoft.CSharp.RuntimeBinder
  summary: Represents an error that occurs when a dynamic bind in the C# runtime binder is processed.
  syntax:
    content: 'public class RuntimeBinderException : System.Exception'
    content.vb: >-
      Public Class RuntimeBinderException
          Inherits System.Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor
  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor
  id: '#ctor'
  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  langs:
  - csharp
  - vb
  name: RuntimeBinderException()
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.RuntimeBinderException()
  type: Constructor
  source:
    remote:
      path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 18
  assemblies:
  - Microsoft.CSharp
  namespace: Microsoft.CSharp.RuntimeBinder
  summary: Initializes a new instance of the <xref href="Microsoft.CSharp.RuntimeBinder.RuntimeBinderException" data-throw-if-not-resolved="false"></xref> class.
  syntax:
    content: public RuntimeBinderException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)
  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  langs:
  - csharp
  - vb
  name: RuntimeBinderException(String)
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.RuntimeBinderException(System.String)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 27
  assemblies:
  - Microsoft.CSharp
  namespace: Microsoft.CSharp.RuntimeBinder
  summary: Initializes a new instance of the <xref href="Microsoft.CSharp.RuntimeBinder.RuntimeBinderException" data-throw-if-not-resolved="false"></xref> class that has a specified error message.
  syntax:
    content: public RuntimeBinderException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)
  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  langs:
  - csharp
  - vb
  name: RuntimeBinderException(String, System.Exception)
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.RuntimeBinderException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.CSharp/ref/Microsoft.CSharp.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/Microsoft.CSharp/ref/Microsoft.CSharp.cs
    startLine: 62
  assemblies:
  - Microsoft.CSharp
  namespace: Microsoft.CSharp.RuntimeBinder
  summary: Initializes a new instance of the <xref href="Microsoft.CSharp.RuntimeBinder.RuntimeBinderException" data-throw-if-not-resolved="false"></xref> class that has a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public RuntimeBinderException(string message, System.Exception innerException)
    content.vb: Public Sub New(message As String, innerException As System.Exception)
    parameters:
    - id: message
      type: System.String
      description: The error message that explains the reason for the exception.
    - id: innerException
      type: System.Exception
      description: The exception that is the cause of the current exception, or a null reference if no inner exception is specified.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.CSharp.RuntimeBinder
  isExternal: false
  name: Microsoft.CSharp.RuntimeBinder
  fullName: Microsoft.CSharp.RuntimeBinder
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
