items:
- uid: System.Security.Authentication.AuthenticationException
  commentId: T:System.Security.Authentication.AuthenticationException
  id: AuthenticationException
  parent: System.Security.Authentication
  children:
  - System.Security.Authentication.AuthenticationException.#ctor
  - System.Security.Authentication.AuthenticationException.#ctor(System.String)
  - System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: AuthenticationException
  fullName: System.Security.Authentication.AuthenticationException
  type: Class
  source:
    remote:
      path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: AuthenticationException
    path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
    startLine: 11
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: The exception that is thrown when authentication fails for an authentication stream.
  syntax:
    content: 'public class AuthenticationException : Exception'
    content.vb: >-
      Public Class AuthenticationException
          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Security.Authentication.AuthenticationException.#ctor
  commentId: M:System.Security.Authentication.AuthenticationException.#ctor
  id: '#ctor'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  - vb
  name: AuthenticationException()
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException()
  type: Constructor
  source:
    remote:
      path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
    startLine: 13
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: Initializes a new instance of the <xref href="System.Security.Authentication.AuthenticationException" data-throw-if-not-resolved="false"></xref> class with no message.
  syntax:
    content: public AuthenticationException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String)
  commentId: M:System.Security.Authentication.AuthenticationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  - vb
  name: AuthenticationException(String)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
    startLine: 14
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: Initializes a new instance of the <xref href="System.Security.Authentication.AuthenticationException" data-throw-if-not-resolved="false"></xref> class with the specified message.
  syntax:
    content: public AuthenticationException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: A <xref href="System.String" data-throw-if-not-resolved="false"></xref> that describes the authentication failure.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  commentId: M:System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  - vb
  name: AuthenticationException(String, Exception)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Net.Security/ref/System.Net.Security.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Net.Security/ref/System.Net.Security.cs
    startLine: 119
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: Initializes a new instance of the <xref href="System.Security.Authentication.AuthenticationException" data-throw-if-not-resolved="false"></xref> class with the specified message and inner exception.
  syntax:
    content: public AuthenticationException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: A <xref href="System.String" data-throw-if-not-resolved="false"></xref> that describes the authentication failure.
    - id: innerException
      type: System.Exception
      description: The <xref href="System.Exception" data-throw-if-not-resolved="false"></xref> that is the cause of the current exception.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Security.Authentication
  isExternal: false
  name: System.Security.Authentication
  fullName: System.Security.Authentication
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
