items:
- uid: System.Runtime.InteropServices.SEHException
  commentId: T:System.Runtime.InteropServices.SEHException
  id: SEHException
  parent: System.Runtime.InteropServices
  children:
  - System.Runtime.InteropServices.SEHException.#ctor
  - System.Runtime.InteropServices.SEHException.#ctor(System.String)
  - System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)
  - System.Runtime.InteropServices.SEHException.CanResume
  langs:
  - csharp
  - vb
  name: SEHException
  fullName: System.Runtime.InteropServices.SEHException
  type: Class
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: SEHException
    path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
    startLine: 19
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: 'Represents structured exception handling (SEH) errors. '
  syntax:
    content: 'public class SEHException : Exception'
    content.vb: >-
      Public Class SEHException
          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Runtime.InteropServices.SEHException.#ctor
  commentId: M:System.Runtime.InteropServices.SEHException.#ctor
  id: '#ctor'
  parent: System.Runtime.InteropServices.SEHException
  langs:
  - csharp
  - vb
  name: SEHException()
  fullName: System.Runtime.InteropServices.SEHException.SEHException()
  type: Constructor
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: .ctor
    path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
    startLine: 22
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: 'Initializes a new instance of the <xref href="System.Runtime.InteropServices.SEHException" data-throw-if-not-resolved="false"></xref> class. '
  syntax:
    content: public SEHException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.SEHException.#ctor(System.String)
  commentId: M:System.Runtime.InteropServices.SEHException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.InteropServices.SEHException
  langs:
  - csharp
  - vb
  name: SEHException(String)
  fullName: System.Runtime.InteropServices.SEHException.SEHException(System.String)
  type: Constructor
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: .ctor
    path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
    startLine: 27
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: Initializes a new instance of the <xref href="System.Runtime.InteropServices.SEHException" data-throw-if-not-resolved="false"></xref> class with a specified message.
  syntax:
    content: public SEHException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: 'The message that indicates the reason for the exception. '
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)
  commentId: M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.InteropServices.SEHException
  langs:
  - csharp
  - vb
  name: SEHException(String, Exception)
  fullName: System.Runtime.InteropServices.SEHException.SEHException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: .ctor
    path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
    startLine: 32
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: Initializes a new instance of the <xref href="System.Runtime.InteropServices.SEHException" data-throw-if-not-resolved="false"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public SEHException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: 'The error message that explains the reason for the exception. '
    - id: inner
      type: System.Exception
      description: 'The exception that is the cause of the current exception. If the <em>inner</em> parameter is not null, the current exception is raised in a catch block that handles the inner exception. '
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.SEHException.CanResume
  commentId: M:System.Runtime.InteropServices.SEHException.CanResume
  id: CanResume
  parent: System.Runtime.InteropServices.SEHException
  langs:
  - csharp
  - vb
  name: CanResume()
  fullName: System.Runtime.InteropServices.SEHException.CanResume()
  type: Method
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: CanResume
    path: src/mscorlib/src/System/Runtime/InteropServices/SEHException.cs
    startLine: 48
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: Indicates whether the exception can be recovered from, and whether the code can continue from the point at which the exception was thrown.
  syntax:
    content: public virtual bool CanResume()
    content.vb: Public Overridable Function CanResume As Boolean
    return:
      type: System.Boolean
      description: Always false, because resumable exceptions are not implemented.
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: System.Runtime.InteropServices
  isExternal: false
  name: System.Runtime.InteropServices
  fullName: System.Runtime.InteropServices
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  fullName: System.Boolean
